optimized yaml

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -41,7 +41,7 @@ jobs:
         if: always()
         run: chown -R 1000:1000 .
 
-  full-test-assignment4:
+  full-test-assignment4-buildroot:
     container: cuaesd/aesd-autotest:24-assignment4-buildroot
     runs-on: self-hosted
     timeout-minutes: 120
@@ -62,36 +62,36 @@ jobs:
         if: always()
         run: chown -R 1000:1000 .
 
-  full-test-assignment5buildroot:
-    container: cuaesd/aesd-autotest:24-assignment5-buildroot
-    runs-on: self-hosted
-    timeout-minutes: 120
-    steps:
-      - uses: actions/checkout@v2
-      - name: Checkout submodules
-        run: git submodule update --init --recursive
-      - name: Cleanup previous runs
-        run: killall -9 qemu-system-aarch64 || true
-      - name: Install sshpass
-        run: |
-          apt-get update
-          apt-get install -y sshpass
-      - name: Run full test
-        run: ./full-test.sh
-      - name: Fix workspace permissions
-        if: always()
-        run: chown -R 1000:1000 .
+#  full-test-assignment5buildroot:
+#    container: cuaesd/aesd-autotest:24-assignment5-buildroot
+#    runs-on: self-hosted
+#    timeout-minutes: 120
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Checkout submodules
+#        run: git submodule update --init --recursive
+#      - name: Cleanup previous runs
+#        run: killall -9 qemu-system-aarch64 || true
+#      - name: Install sshpass
+#        run: |
+#          apt-get update
+#          apt-get install -y sshpass
+#      - name: Run full test
+#        run: ./full-test.sh
+#      - name: Fix workspace permissions
+#        if: always()
+#        run: chown -R 1000:1000 .
 
-  full-test-assignment5final:
-    needs: full-test-assignment5buildroot
-    runs-on: self-hosted
-    steps:
-      - uses: actions/checkout@v2
-      - name: Checkout submodules
-        run: git submodule update --init --recursive
-      - name: Cleanup previous runs
-        run: killall -9 qemu-system-aarch64 || true
-      - name: Fix workspace permissions
-        run: chown -R $USER:$USER .
-      - name: Run full test
-        run: ./full-test.sh
+#  full-test-assignment5final:
+#    needs: full-test-assignment5buildroot
+#    runs-on: self-hosted
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Checkout submodules
+#        run: git submodule update --init --recursive
+#      - name: Cleanup previous runs
+#        run: killall -9 qemu-system-aarch64 || true
+#      - name: Fix workspace permissions
+#        run: chown -R $USER:$USER .
+#      - name: Run full test
+#        run: ./full-test.sh
